#!/usr/bin/env python3
"""Regenerate the self-contained Kaggle notebook from the `src/ml/` sources.

`build_notebook.py` regenerates the **self-contained** notebook from the `src/ml/` sources
(base64-embedded, so there is a single source of truth — the same code the tests use). **Re-run it after
any change under `src/ml/`.** You upload exactly two things to Kaggle: the `data/exports/` folder and
`notebooks/train_a3tgcn.ipynb`.

The generated notebook: (1) pip-installs deps, (2) base64-decodes the embedded modules to
`/kaggle/working/ml/`, (3) locates the uploaded `data/exports/` under `/kaggle/input/`, (4) runs training.
"""
from __future__ import annotations

import base64
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "src" / "ml"
OUT = REPO / "notebooks" / "train_a3tgcn.ipynb"
MODULES = ["__init__.py", "config.py", "dataset.py", "model.py", "losses.py", "train.py"]


def _code(src: str) -> dict:
    return {"cell_type": "code", "metadata": {}, "execution_count": None, "outputs": [],
            "source": src.splitlines(keepends=True)}


def _md(src: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": src.splitlines(keepends=True)}


def build() -> dict:
    embedded = {m: base64.b64encode((SRC / m).read_bytes()).decode() for m in MODULES}
    payload = json.dumps(embedded)

    header = (
        "# A3T-GCN — Ukraine Air-Alert Forecasting (auto-generated)\n\n"
        "Generated by `scripts/build_notebook.py` from `src/ml/` (base64-embedded — single source of "
        "truth, the same code the tests use). **Do not edit by hand**; edit `src/ml/` and re-run the "
        "builder.\n\n"
        "**Setup:** attach the `data/exports/` folder as a Kaggle Dataset (must contain "
        "`airraid_analytical_long.parquet`, `edges.parquet`, `oblasts.parquet`). Enable GPU."
    )
    install = "!pip install -q torch_geometric wandb weave tqdm scikit-learn pyarrow"
    writer = (
        "import base64, json, pathlib\n"
        f"MODULES = json.loads({payload!r})\n"
        "pkg = pathlib.Path('/kaggle/working/ml'); pkg.mkdir(parents=True, exist_ok=True)\n"
        "for _name, _b64 in MODULES.items():\n"
        "    (pkg / _name).write_bytes(base64.b64decode(_b64))\n"
        "print('wrote modules:', list(MODULES))"
    )
    runner = (
        "import os, sys, glob, pathlib\n"
        "sys.path.insert(0, '/kaggle/working')\n"
        "# locate the uploaded data/exports bundle anywhere under /kaggle/input\n"
        "cands = glob.glob('/kaggle/input/**/airraid_analytical_long.parquet', recursive=True)\n"
        "assert cands, 'Attach data/exports/ as a Kaggle Dataset (needs airraid_analytical_long.parquet)'\n"
        "os.environ['AIRRAID_EXPORTS_DIR'] = str(pathlib.Path(cands[0]).parent)\n"
        "print('exports dir:', os.environ['AIRRAID_EXPORTS_DIR'])\n"
        "from ml.config import Config\n"
        "from ml.train import main\n"
        "main(Config())"
    )

    cells = [_md(header), _code(install), _code(writer), _code(runner)]
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"name": "python3", "display_name": "Python 3"},
            "language_info": {"name": "python"},
            "accelerator": "GPU",
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def main() -> None:
    nb = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(nb, indent=1))
    print(f"wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size} bytes); embedded {len(MODULES)} modules: {MODULES}")


if __name__ == "__main__":
    main()
